#include "imgui.h"
#include "imgui_impl_glfw.h"
#include "imgui_impl_opengl3.h"

#include "function/glfw.cpp"
#include "function/aircraft.cpp"

#include <cstdio>
#include <cmath>
#include <GLFW/glfw3.h>

#include <cstdlib>
#include <ctime>
#include <sstream>
#include <algorithm>
#include <vector>
#include <string>
#include <iomanip>
#include <deque>

using namespace std;

#ifndef IM_PI
#define IM_PI 3.14159265358979323846f
#endif

static float deg_to_rad(float d) { return d * (IM_PI / 180.0f); }
static float rad_to_deg(float r) { return r * (180.0f / IM_PI); }

static constexpr float radar_range_km = 80.0f;

// Runway data structure
struct Runway
{
    std::string name;
    float heading_deg; // true heading
    float x, y; // position in km
    float ils_glideslope_deg = 3.0f;
    float ils_localizer_width_deg = 3.0f;
};

// Waypoint structure
struct Waypoint
{
    std::string name;
    float x, y; // position in km
};

static float angle_difference(float target, float current)
{
    float diff = fmodf(target - current + 540.0f, 360.0f) - 180.0f;
    return diff;
}

void generate_runways(vector<Runway>& runways, bool autogenerated) {
    if (!autogenerated) {

    }
    else {
        runways.push_back({"09", 90.0f, -1.0f, 0.0f});
        runways.push_back({"27", 270.0f, 1.0f, 0.0f});
        runways.push_back({"18", 180.0f, 0.0f, -1.0f});
        runways.push_back({"36", 0.0f, 0.0f, 1.0f});
        runways.push_back({"04", 40.0f, -0.8f, -0.6f});
        runways.push_back({"22", 220.0f, 0.8f, 0.6f});
    }
}

void generate_waypoints(vector<Waypoint>& waypoints, bool autogenerated) {
    if (!autogenerated) {

    }
    else {
        waypoints.push_back({"ALPHA", 20.0f, 30.0f});
        waypoints.push_back({"BRAVO", -25.0f, 35.0f});
        waypoints.push_back({"CHARLIE", 35.0f, -20.0f});
        waypoints.push_back({"DELTA", -30.0f, -25.0f});
        waypoints.push_back({"ECHO", 40.0f, 10.0f});
        waypoints.push_back({"FOXTROT", -15.0f, -40.0f});
    }
}

// Global command log
std::deque<std::string> global_command_log;

// Add to global command log
void addToCommandLog(const std::string& entry) {
    global_command_log.push_back(entry);
    if (global_command_log.size() > 100) {
        global_command_log.pop_front();
    }
}

int main(int, char**)
{
    srand((unsigned)time(nullptr));

    glfwSetErrorCallback(glfw_error_callback);
    if (!glfwInit()) return 1;

    #if __APPLE__
        const char* glsl_version = "#version 150";
        glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
        glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
        glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
        glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
    #else
        const char* glsl_version = "#version 130";
        glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
        glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 0);
    #endif

    GLFWwindow* window = glfwCreateWindow(1280, 768, "Air Traffic Controller", nullptr, nullptr);
    if (window == nullptr) return 1;

    glfwMakeContextCurrent(window);
    glfwSwapInterval(1);

    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO();
    ImGui::StyleColorsDark();

    ImGui_ImplGlfw_InitForOpenGL(window, true);
    ImGui_ImplOpenGL3_Init(glsl_version);

    // Setup runways
    std::vector<Runway> runways;
    generate_runways(runways, 1);

    // Setup waypoints
    std::vector<Waypoint> waypoints;
    generate_waypoints(waypoints, 1);

    // Wind
    float wind_heading = (float)(rand() % 360);
    float wind_speed_kts = 5.0f + (rand() % 25); // 5-30 kts

    std::vector<Aircraft> aircraft; // list of aircrafts
    const int initial_ac_count = 12;
    for (int i = 0; i < initial_ac_count; ++i)
    {
        Aircraft a;
        generateAircraft(aircraft, a, radar_range_km, i, false);
        aircraft.push_back(a);
    }
    int selected_index = -1;

    float camera_x = 0.0f;
    float camera_y = 0.0f;
    float zoom_level = 1.0f;
    bool is_panning = false;
    ImVec2 last_mouse_pos;

    double last_time = glfwGetTime();
    float animation_speed = 1.0f; // Time multiplier
    float last_sweep_angle = 0.0f; // For smooth radar sweep

    const float right_panel_width = 450.0f;

    // Command input variables
    static char command_buf[256] = "";
    static std::string command_feedback = "";
    static std::vector<std::string> history;
    static int history_index = -1;

    // Aircraft command buffer for selected aircraft
    static char ac_command_buf[256] = "";
    static bool show_help = false;

    // Overflight spawn timer
    float overflight_spawn_timer = 0.0f;

    while (!glfwWindowShouldClose(window))
    {
        double now = glfwGetTime();
        float dt = (float)(now - last_time) * animation_speed;
        if (dt <= 0.0f) dt = 1.0f / 60.0f;
        last_time = now;

        // Update radar sweep angle smoothly
        last_sweep_angle = fmodf(last_sweep_angle + 0.8f * dt, 2.0f * IM_PI);

        int display_w, display_h;
        glfwGetFramebufferSize(window, &display_w, &display_h);

        glfwPollEvents();

        // Handle F1 key for help
        if (ImGui::IsKeyPressed(ImGuiKey_F1)) {
            show_help = !show_help;
        }

        // Random overflight generation
        overflight_spawn_timer += dt;
        // Random overflight generation
overflight_spawn_timer += dt;
if (overflight_spawn_timer >= 4.0f) { // Every 2 seconds (less frequent)
    overflight_spawn_timer = 0.0f;
    if (rand() % 100 == 0) { // 20% chance every 2 seconds

        Aircraft a;
        std::ostringstream ss;
        ss << "OF" << std::setw(2) << std::setfill('0') << (aircraft.size() + 1);
        a.callsign = ss.str();

        // Spawn outside radar bounds but aimed to cross through
        float spawn_distance = radar_range_km * 1.5f; // Spawn 50% outside radar range

        // Choose spawn side (0=top, 1=right, 2=bottom, 3=left)
        int spawn_side = rand() % 4;

        // Target point (somewhere on opposite side or within radar area)
        float target_x, target_y;

        // Set spawn position based on side
        switch(spawn_side) {
            case 0: // Top
                a.x = ((float)rand() / RAND_MAX - 0.5f) * radar_range_km * 1.5f;
                a.y = spawn_distance;
                // Target somewhere on bottom half
                target_x = ((float)rand() / RAND_MAX - 0.5f) * radar_range_km * 0.8f;
                target_y = -spawn_distance * 0.5f;
                break;
            case 1: // Right
                a.x = spawn_distance;
                a.y = ((float)rand() / RAND_MAX - 0.5f) * radar_range_km * 1.5f;
                // Target somewhere on left half
                target_x = -spawn_distance * 0.5f;
                target_y = ((float)rand() / RAND_MAX - 0.5f) * radar_range_km * 0.8f;
                break;
            case 2: // Bottom
                a.x = ((float)rand() / RAND_MAX - 0.5f) * radar_range_km * 1.5f;
                a.y = -spawn_distance;
                // Target somewhere on top half
                target_x = ((float)rand() / RAND_MAX - 0.5f) * radar_range_km * 0.8f;
                target_y = spawn_distance * 0.5f;
                break;
            case 3: // Left
                a.x = -spawn_distance;
                a.y = ((float)rand() / RAND_MAX - 0.5f) * radar_range_km * 1.5f;
                // Target somewhere on right half
                target_x = spawn_distance * 0.5f;
                target_y = ((float)rand() / RAND_MAX - 0.5f) * radar_range_km * 0.8f;
                break;
        }

        // Calculate heading to target
        float dx = target_x - a.x;
        float dy = target_y - a.y;
        float target_heading = fmodf(rad_to_deg(atan2f(dy, dx)) + 360.0f, 360.0f);

        a.is_overflight = true;
        a.altitude_ft = 35000.0f + (rand() % 50) * 100; // 35000-40000 ft
        a.squawk_code = "----";
        a.heading_deg = target_heading;
        a.speed_kts = 450.0f + (rand() % 100); // 450-550 kts (typical cruise)
        a.selected = false;

        // Set targets for overflight
        a.target_altitude_ft = a.altitude_ft;
        a.target_heading_deg = a.heading_deg;
        a.target_speed_kts = a.speed_kts;
        a.pending_altitude_ft = a.altitude_ft;
        a.pending_heading_deg = a.heading_deg;
        a.pending_speed_kts = a.speed_kts;

        aircraft.push_back(a);
    }
}

        // Update aircraft
        for (size_t idx = 0; idx < aircraft.size(); ++idx)
        {
            auto& a = aircraft[idx];

            // Calculate distance from airport (center) in nautical miles
            float distance_km = sqrtf(a.x * a.x + a.y * a.y);
            float distance_nm = distance_km * 0.539957f; // Convert km to nautical miles

            // Check if aircraft is beyond 67 nautical miles
            if (distance_nm > 67.0f) {
                // Log removal for debugging
                if (!a.is_overflight) {
                    addToCommandLog("[SYSTEM]: " + a.callsign + " left airspace (>67nm)");
                }

                // Remove aircraft
                if (selected_index == (int)idx) {
                    selected_index = -1;
                } else if (selected_index > (int)idx) {
                    selected_index--;
                }
                aircraft.erase(aircraft.begin() + idx);
                idx--;
                continue;
            }

            // Also check if aircraft is way out of bounds (safety cleanup)
            if (distance_km > radar_range_km * 2.0f) { // 2x radar range as backup
                // Remove aircraft
                if (selected_index == (int)idx) {
                    selected_index = -1;
                } else if (selected_index > (int)idx) {
                    selected_index--;
                }
                aircraft.erase(aircraft.begin() + idx);
                idx--;
                continue;
            }

            if (a.response_timer > 0.0f)
                a.response_timer -= dt;

            // Update emergency timer
            if (a.emergency != EMERGENCY_NONE && !a.is_overflight)
            {
                a.emergency_timer -= dt;
                if (a.emergency_timer <= 0.0f)
                {
                    // Emergency critical - lose altitude rapidly
                    a.target_altitude_ft = std::max(0.0f, a.target_altitude_ft - 2000.0f * dt);
                    a.pending_altitude_ft = a.target_altitude_ft;
                }
            }

            // Check if aircraft should be removed (crashed or landed)
            if (a.altitude_ft <= 0.0f) {
                // Remove aircraft
                if (selected_index == (int)idx) {
                    selected_index = -1;
                } else if (selected_index > (int)idx) {
                    selected_index--;
                }
                aircraft.erase(aircraft.begin() + idx);
                idx--;
                continue;
            }

            if (a.command_delay > 0.0f)
            {
                a.command_delay -= dt;
                if (a.command_delay <= 0.0f)
                {
                    a.target_altitude_ft = a.pending_altitude_ft;
                    a.target_heading_deg = a.pending_heading_deg;
                    a.target_speed_kts = a.pending_speed_kts;
                    a.has_pending_command = false;
                }
            }

            // Handle go around
            if (a.go_around) {
                a.go_around_timer -= dt;
                if (a.go_around_timer <= 0.0f) {
                    a.go_around = false;
                    a.ils_active = false;
                    a.cleared_to_land = false;
                    a.target_altitude_ft = 3000.0f;
                    a.target_speed_kts = 180.0f;
                    a.addCommandToHistory("Go around", "Going around, climbing to 3000");
                }
            }

            // ILS approach guidance
            if (a.ils_active && !a.ils_runway.empty())
            {
                // Find the runway
                for (const auto& rwy : runways)
                {
                    if (rwy.name == a.ils_runway)
                    {
                        // Calculate vector from aircraft to runway
                        float dx_to_rwy = rwy.x - a.x;
                        float dy_to_rwy = rwy.y - a.y;
                        float dist_to_rwy = sqrtf(dx_to_rwy * dx_to_rwy + dy_to_rwy * dy_to_rwy);

                        // Calculate runway heading in radians
                        float rwy_heading_rad = deg_to_rad(rwy.heading_deg);

                        // Calculate aircraft's angle to runway centerline
                        float angle_to_rwy = atan2f(dy_to_rwy, dx_to_rwy);
                        float deviation_angle = angle_difference(rad_to_deg(angle_to_rwy), rwy.heading_deg + 180.0f);

                        // Convert angular deviation to lateral deviation (meters)
                        a.ils_localizer_deviation = dist_to_rwy * 1000.0f * tanf(deg_to_rad(deviation_angle));

                        // If close enough to centerline, consider established
                        if (fabs(a.ils_localizer_deviation) < 500.0f && dist_to_rwy < 20.0f) {
                            a.ils_established = true;
                        }

                        // Auto-align to localizer if established
                        if (a.ils_established) {
                            // Calculate intercept heading
                            float intercept_heading = rwy.heading_deg;
                            if (a.ils_localizer_deviation > 100.0f) {
                                intercept_heading = fmodf(rwy.heading_deg - 10.0f + 360.0f, 360.0f);
                            } else if (a.ils_localizer_deviation < -100.0f) {
                                intercept_heading = fmodf(rwy.heading_deg + 10.0f + 360.0f, 360.0f);
                            }

                            if (dist_to_rwy > 1.0f) {
                                a.target_heading_deg = intercept_heading;
                            }
                        }

                        // Standard ILS glideslope is 3 degrees
                        float expected_alt_ft = dist_to_rwy * 1000.0f * tanf(deg_to_rad(3.0f)) * 3.28084f;
                        a.ils_glideslope_deviation = a.altitude_ft - expected_alt_ft;

                        // Auto-adjust altitude on glideslope if cleared to land
                        if (a.cleared_to_land && a.ils_established && dist_to_rwy > 1.0f) {
                            float gs_alt = dist_to_rwy * 1000.0f * tanf(deg_to_rad(3.0f)) * 3.28084f;
                            a.target_altitude_ft = gs_alt;

                            // Adjust speed for approach
                            if (dist_to_rwy < 10.0f) {
                                a.target_speed_kts = 140.0f;
                            } else if (dist_to_rwy < 20.0f) {
                                a.target_speed_kts = 160.0f;
                            }

                            // Check for landing
                            if (dist_to_rwy < 0.5f && a.altitude_ft < 100.0f) {
                                // Landed - remove aircraft
                                addToCommandLog("[ATC]: " + a.callsign + " cleared to land");
                                addToCommandLog("[" + a.callsign + "]: " + a.callsign + ", runway " + rwy.name + ", landed");
                                if (selected_index == (int)idx) {
                                    selected_index = -1;
                                } else if (selected_index > (int)idx) {
                                    selected_index--;
                                }
                                aircraft.erase(aircraft.begin() + idx);
                                idx--;
                                continue;
                            }
                        } else if (dist_to_rwy < 2.0f && !a.cleared_to_land && !a.go_around) {
                            // Too close to runway without clearance - go around
                            a.go_around = true;
                            a.go_around_timer = 2.0f;
                            a.target_altitude_ft = 3000.0f;
                            a.target_speed_kts = 180.0f;
                            a.addCommandToHistory("Go around", "Going around, not cleared to land");
                        }

                        break;
                    }
                }
            }

            // Handle hold pattern
            if (a.in_hold_pattern) {
                if (a.hold_duration > 0.0f) {
                    a.hold_timer += dt;
                    if (a.hold_timer >= a.hold_duration) {
                        a.in_hold_pattern = false;
                        a.addCommandToHistory("Resume", "Resuming normal navigation");
                    }
                }

                if (!a.hold_entry_complete) {
                    // Turn to hold heading
                    float hdg_diff = angle_difference(a.hold_heading, a.heading_deg);
                    if (fabs(hdg_diff) < 5.0f) {
                        a.hold_entry_complete = true;
                    } else {
                        a.target_heading_deg = a.hold_heading;
                    }
                } else {
                    // Standard racetrack pattern
                    // Simplified hold pattern
                    a.target_heading_deg = a.hold_heading;
                    a.target_altitude_ft = a.hold_altitude;
                }
            }

            // Handle direct to waypoint
            if (a.direct_to_active) {
                float dx = a.direct_to_x - a.x;
                float dy = a.direct_to_y - a.y;
                float dist = sqrtf(dx*dx + dy*dy);

                if (dist < a.direct_tolerance_km) {
                    a.direct_to_active = false;
                } else {
                    // Calculate heading to waypoint
                    float desired_heading = fmodf(rad_to_deg(atan2f(dy, dx)) + 360.0f, 360.0f);
                    a.target_heading_deg = desired_heading;
                }
            }

            const float max_alt_rate = 40.00f;
            const float alt_accel = 4.0f;
            const float max_speed_rate = 3.0f;
            const float speed_accel = 0.5f;

            // Altitude transition
            float alt_diff = a.target_altitude_ft - a.altitude_ft;
            if (fabs(alt_diff) > 1.0f)
            {
                float desired_rate = 0.0f;
                float distance_factor = sqrtf(2.0f * alt_accel * fabs(alt_diff));

                if (alt_diff > 0)
                    desired_rate = std::min(max_alt_rate, distance_factor);
                else
                    desired_rate = -std::min(max_alt_rate, distance_factor);

                float rate_diff = desired_rate - a.altitude_rate_fps;
                if (fabs(rate_diff) > 0.1f)
                {
                    float accel_step = alt_accel * dt;
                    if (rate_diff > 0)
                        a.altitude_rate_fps += std::min(accel_step, rate_diff);
                    else
                        a.altitude_rate_fps += std::max(-accel_step, rate_diff);
                }
                else
                {
                    a.altitude_rate_fps = desired_rate;
                }

                float new_altitude = a.altitude_ft + a.altitude_rate_fps * dt;
                new_altitude = std::max(0.0f, new_altitude);

                if ((alt_diff > 0 && new_altitude >= a.target_altitude_ft) ||
                    (alt_diff < 0 && new_altitude <= a.target_altitude_ft))
                {
                    a.altitude_ft = a.target_altitude_ft;
                    a.altitude_rate_fps = 0.0f;
                }
                else
                {
                    a.altitude_ft = new_altitude;
                }
            }
            else
            {
                a.altitude_ft = a.target_altitude_ft;
                a.altitude_rate_fps = 0.0f;
            }

            // Heading transition
            float heading_diff = angle_difference(a.target_heading_deg, a.heading_deg);
            if (fabs(heading_diff) > 0.5f)
            {
                float turn_rate = 2.5f * dt;
                if (heading_diff > 0)
                    a.heading_deg += std::min(turn_rate, heading_diff);
                else
                    a.heading_deg += std::max(-turn_rate, heading_diff);

                a.heading_deg = fmodf(a.heading_deg + 360.0f, 360.0f);
            }
            else
            {
                a.heading_deg = a.target_heading_deg;
            }

            // Speed transition
            float speed_diff = a.target_speed_kts - a.speed_kts;
            if (fabs(speed_diff) > 0.5f)
            {
                float desired_rate = 0.0f;
                float distance_factor = sqrtf(2.0f * speed_accel * fabs(speed_diff));

                if (speed_diff > 0)
                    desired_rate = std::min(max_speed_rate, distance_factor);
                else
                    desired_rate = -std::min(max_speed_rate, distance_factor);

                float rate_diff = desired_rate - a.speed_rate_kps;
                if (fabs(rate_diff) > 0.05f)
                {
                    float accel_step = speed_accel * dt;
                    if (rate_diff > 0)
                        a.speed_rate_kps += std::min(accel_step, rate_diff);
                    else
                        a.speed_rate_kps += std::max(-accel_step, rate_diff);
                }
                else
                {
                    a.speed_rate_kps = desired_rate;
                }

                float new_speed = a.speed_kts + a.speed_rate_kps * dt;
                new_speed = std::max(0.0f, new_speed);

                if ((speed_diff > 0 && new_speed >= a.target_speed_kts) ||
                    (speed_diff < 0 && new_speed <= a.target_speed_kts))
                {
                    a.speed_kts = a.target_speed_kts;
                    a.speed_rate_kps = 0.0f;
                }
                else
                {
                    a.speed_kts = new_speed;
                }
            }
            else
            {
                a.speed_kts = a.target_speed_kts;
                a.speed_rate_kps = 0.0f;
            }

            // Position update
            float speed_kmh = a.speed_kts * 1.852f;
            float speed_kms = speed_kmh / 3600.0f;
            float ang = deg_to_rad(a.heading_deg);
            a.x += cosf(ang) * speed_kms * dt;
            a.y += sinf(ang) * speed_kms * dt;
        }

        // Conflict detection
        const float conflict_horiz_km = 5.0f;
        const float conflict_horiz_km2 = conflict_horiz_km * conflict_horiz_km;
        const float conflict_vert_ft = 1000.0f;

        std::vector<std::pair<int, int>> conflicts;
        for (size_t i = 0; i < aircraft.size(); ++i)
        {
            for (size_t j = i + 1; j < aircraft.size(); ++j)
            {
                float dx = aircraft[i].x - aircraft[j].x;
                float dy = aircraft[i].y - aircraft[j].y;
                float d2 = dx * dx + dy * dy;
                float dz = abs(aircraft[i].altitude_ft - aircraft[j].altitude_ft);
                if (d2 <= conflict_horiz_km2 && dz <= conflict_vert_ft)
                {
                    conflicts.emplace_back((int)i, (int)j);
                }
            }
        }

        ImGui_ImplOpenGL3_NewFrame();
        ImGui_ImplGlfw_NewFrame();
        ImGui::NewFrame();

        // Show help window if F1 pressed
        if (show_help) {
            ImGui::Begin("Command Help", &show_help, ImGuiWindowFlags_AlwaysAutoResize);
            ImGui::TextColored(ImVec4(1.0f, 1.0f, 0.0f, 1.0f), "ATC COMMANDS REFERENCE");
            ImGui::Separator();
            ImGui::Text("Format: <callsign> <command> <parameters>");
            ImGui::Separator();
            ImGui::TextColored(ImVec4(0.4f, 1.0f, 0.4f, 1.0f), "Altitude Commands:");
            ImGui::Text("  CLIMB TO <altitude> - Climb to specified altitude");
            ImGui::Text("  DESCEND TO <altitude> - Descend to specified altitude");
            ImGui::Text("  FL<level> - Set flight level (FL370 = 37000 ft)");
            ImGui::Separator();
            ImGui::TextColored(ImVec4(0.4f, 1.0f, 0.4f, 1.0f), "Heading Commands:");
            ImGui::Text("  HEADING <degrees> - Turn to specified heading");
            ImGui::Text("  TURN LEFT <degrees> - Turn left specified degrees");
            ImGui::Text("  TURN RIGHT <degrees> - Turn right specified degrees");
            ImGui::Separator();
            ImGui::TextColored(ImVec4(0.4f, 1.0f, 0.4f, 1.0f), "Speed Commands:");
            ImGui::Text("  SPEED <knots> - Set speed in knots");
            ImGui::Separator();
            ImGui::TextColored(ImVec4(0.4f, 1.0f, 0.4f, 1.0f), "ILS & Approach:");
            ImGui::Text("  ILS <runway> - Activate ILS for runway");
            ImGui::Text("  CLEARED TO LAND - Clear aircraft to land");
            ImGui::Text("  GO AROUND - Command go around");
            ImGui::Separator();
            ImGui::TextColored(ImVec4(0.4f, 1.0f, 0.4f, 1.0f), "Navigation:");
            ImGui::Text("  DIRECT TO <waypoint> - Fly direct to waypoint");
            ImGui::Text("  HOLD <heading> [<minutes>] - Enter hold pattern");
            ImGui::Text("  RESUME - Resume normal navigation");
            ImGui::Separator();
            ImGui::TextColored(ImVec4(0.4f, 1.0f, 0.4f, 1.0f), "Other:");
            ImGui::Text("  SQUAWK <code> - Set transponder code");
            ImGui::Text("  REMOVE - Remove aircraft from simulation");
            ImGui::Separator();
            if (ImGui::Button("Close")) {
                show_help = false;
            }
            ImGui::End();
        }

        float radar_width = display_w - right_panel_width;
        float radar_height = display_h;

        ImGuiWindowFlags window_flags = ImGuiWindowFlags_NoTitleBar |
            ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove |
            ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoSavedSettings;

        ImGui::SetNextWindowPos(ImVec2(0, 0), ImGuiCond_Always);
        ImGui::SetNextWindowSize(ImVec2(radar_width, radar_height), ImGuiCond_Always);

        ImGui::Begin("Radar", nullptr, window_flags);

        ImDrawList* draw_list = ImGui::GetWindowDrawList();
        ImVec2 win_pos = ImGui::GetWindowPos();
        ImVec2 win_size = ImGui::GetWindowSize();
        ImVec2 center(win_pos.x + win_size.x * 0.5f, win_pos.y + win_size.y * 0.5f);
        float radius_max = (win_size.x < win_size.y ? win_size.x : win_size.y) * 0.45f;

        ImVec2 mouse_pos = ImGui::GetMousePos();
        bool is_radar_hovered = ImGui::IsWindowHovered(ImGuiHoveredFlags_RootAndChildWindows);

        if (is_radar_hovered)
        {
            float wheel = io.MouseWheel;
            if (wheel != 0.0f)
            {
                float zoom_factor = 1.0f + wheel * 0.15f;
                float new_zoom = zoom_level * zoom_factor;
                new_zoom = std::max(0.2f, std::min(5.0f, new_zoom));

                ImVec2 mouse_rel(mouse_pos.x - center.x, mouse_pos.y - center.y);
                float scale_before = radius_max / (radar_range_km * zoom_level);
                float scale_after = radius_max / (radar_range_km * new_zoom);

                camera_x += mouse_rel.x / scale_before - mouse_rel.x / scale_after;
                camera_y -= mouse_rel.y / scale_before - mouse_rel.y / scale_after;

                zoom_level = new_zoom;
            }
        }

        bool shift_held = io.KeyShift;
        bool should_pan = is_radar_hovered && (
            (ImGui::IsMouseDown(0) && shift_held) ||
            ImGui::IsMouseDown(2) ||
            ImGui::IsMouseDown(1)
        );

        if (should_pan)
        {
            if (!is_panning)
            {
                is_panning = true;
                last_mouse_pos = mouse_pos;
            }
            else
            {
                ImVec2 delta(mouse_pos.x - last_mouse_pos.x, mouse_pos.y - last_mouse_pos.y);
                float scale = radius_max / (radar_range_km * zoom_level);
                camera_x -= delta.x / scale;
                camera_y += delta.y / scale;
                last_mouse_pos = mouse_pos;
            }
        }
        else
        {
            is_panning = false;
        }

        ImU32 col_green = IM_COL32(0, 255, 0, 100);
        ImU32 bg = IM_COL32(0, 20, 0, 200);
        draw_list->AddRectFilled(win_pos, ImVec2(win_pos.x + win_size.x, win_pos.y + win_size.y), bg, 8.0f);

        auto world_to_screen = [&](float wx, float wy)
        {
            float scale = radius_max / (radar_range_km * zoom_level);
            float vx = wx - camera_x;
            float vy = wy - camera_y;
            return ImVec2(center.x + vx * scale, center.y - vy * scale);
        };

        // Draw rings
        const int rings = 4;
        for (int i = 1; i <= rings; ++i)
        {
            float km_radius = (radar_range_km * i) / rings;
            ImVec2 p0 = world_to_screen(0, 0);
            ImVec2 p1 = world_to_screen(km_radius, 0);
            float screen_r = fabs(p1.x - p0.x);
            draw_list->AddCircle(p0, screen_r, col_green, 128, 1.0f);

            float range_nm = km_radius * 0.539957f;
            std::ostringstream ss;
            ss << (int)range_nm << " nm";
            draw_list->AddText(ImVec2(p0.x + screen_r - 30, p0.y - 12), col_green, ss.str().c_str());
        }

        // Draw runways and ILS
        // Draw runways and ILS lines
        ImU32 runway_color = IM_COL32(100, 150, 255, 255);  // Runway - solid color
        ImU32 ils_line_color = IM_COL32(80, 120, 200, 120); // ILS line - lighter and semi-transparent

        for (const auto& rwy : runways)
        {
            ImVec2 rwy_pos = world_to_screen(rwy.x, rwy.y);

            // Draw runway marker
            draw_list->AddCircleFilled(rwy_pos, 8.0f, runway_color);
            draw_list->AddText(ImVec2(rwy_pos.x + 12, rwy_pos.y - 8), runway_color, rwy.name.c_str());

            // Draw extended ILS approach line (15km straight line)
            float ils_angle = deg_to_rad(rwy.heading_deg + 180.0f); // Opposite direction (approach direction)
            float ils_len = 15.0f;  // Extended ILS line length

            ImVec2 ils_end = world_to_screen(
                rwy.x + cosf(ils_angle) * ils_len,
                rwy.y + sinf(ils_angle) * ils_len
            );

            // Draw the extended ILS line (lighter than runway)
            draw_list->AddLine(rwy_pos, ils_end, ils_line_color, 3.0f); // Thicker line for visibility

            // Optional: Add small arrow head at the runway end to show approach direction
            float arrow_len = 0.5f; // 0.5km arrow
            float arrow_angle1 = ils_angle - deg_to_rad(30.0f);
            float arrow_angle2 = ils_angle + deg_to_rad(30.0f);

            ImVec2 arrow_start = world_to_screen(
                rwy.x + cosf(ils_angle) * 1.0f, // Start arrow 1km from runway
                rwy.y + sinf(ils_angle) * 1.0f
            );

            ImVec2 arrow_end1 = world_to_screen(
                rwy.x + cosf(arrow_angle1) * arrow_len,
                rwy.y + sinf(arrow_angle1) * arrow_len
            );

            ImVec2 arrow_end2 = world_to_screen(
                rwy.x + cosf(arrow_angle2) * arrow_len,
                rwy.y + sinf(arrow_angle2) * arrow_len
            );

            // Draw arrow head
            draw_list->AddLine(arrow_start, arrow_end1, ils_line_color, 2.0f);
            draw_list->AddLine(arrow_start, arrow_end2, ils_line_color, 2.0f);
        }

        // Draw waypoints
        ImU32 waypoint_color = IM_COL32(255, 200, 100, 200);
        for (const auto& wp : waypoints)
        {
            ImVec2 wp_pos = world_to_screen(wp.x, wp.y);
            draw_list->AddCircle(wp_pos, 6.0f, waypoint_color, 12, 2.0f);
            draw_list->AddText(ImVec2(wp_pos.x + 10, wp_pos.y - 8), waypoint_color, wp.name.c_str());
        }

        // Radar sweep - use smooth angle to prevent teleporting
        float sweep_length_km = radar_range_km;
        float sx = cosf(last_sweep_angle) * sweep_length_km;
        float sy = sinf(last_sweep_angle) * sweep_length_km;
        ImVec2 sweep_center = world_to_screen(0.0f, 0.0f);
        ImVec2 sweep_tip = world_to_screen(sx, sy);
        ImU32 sweep_color = IM_COL32(120, 255, 120, 255);
        draw_list->AddLine(sweep_center, sweep_tip, sweep_color, 2.0f);

        // Draw axes
        float axis_len_km = radar_range_km;
        ImVec2 left = world_to_screen(-axis_len_km, 0.0f);
        ImVec2 right = world_to_screen(+axis_len_km, 0.0f);
        draw_list->AddLine(left, right, col_green, 1.0f);
        ImVec2 down = world_to_screen(0.0f, -axis_len_km);
        ImVec2 up = world_to_screen(0.0f, +axis_len_km);
        draw_list->AddLine(down, up, col_green, 1.0f);
        ImVec2 c = world_to_screen(0.0f, 0.0f);
        draw_list->AddCircleFilled(c, 3.0f, col_green);

        // Draw aircraft
        for (size_t i = 0; i < aircraft.size(); ++i)
        {
            const Aircraft& a = aircraft[i];
            ImVec2 pos = world_to_screen(a.x, a.y);

            float margin = 100.0f;
            bool on_screen = (pos.x >= win_pos.x - margin && pos.x <= win_pos.x + win_size.x + margin &&
                            pos.y >= win_pos.y - margin && pos.y <= win_pos.y + win_size.y + margin);

            if (!on_screen) continue;

            bool in_conflict = false;
            for (auto& cf : conflicts)
            {
                if ((int)i == cf.first || (int)i == cf.second)
                {
                    in_conflict = true;
                    break;
                }
            }

            ImU32 blip_col;
            // Check for emergency squawks
            if (a.squawk_code == "7500" || a.squawk_code == "7600" || a.squawk_code == "7700" || a.emergency != EMERGENCY_NONE)
                blip_col = IM_COL32(255, 0, 0, 255); // Red for emergency
            else if (a.is_overflight)
                blip_col = IM_COL32(150, 150, 150, 180); // Gray for overflight
            else if (in_conflict)
                blip_col = IM_COL32(255, 64, 64, 255);
            else
                blip_col = IM_COL32(255, 255, 0, 255);

            float blip_radius = (selected_index == (int)i) ? 6.0f : 4.0f;
            draw_list->AddCircleFilled(pos, blip_radius, blip_col);

            float head_rad = deg_to_rad(a.heading_deg);
            ImVec2 head_end(pos.x + cosf(head_rad) * 12.0f, pos.y - sinf(head_rad) * 12.0f);
            draw_list->AddLine(pos, head_end, IM_COL32(200, 200, 200, 180), 1.0f);

            // Draw callsign, FL, and squawk in separate lines
            std::ostringstream ss1, ss2, ss3;
            ss1 << a.callsign;
            ss2 << "FL" << (int)(a.altitude_ft / 100);
            ss3 << a.squawk_code;

            // Callsign
            draw_list->AddText(ImVec2(pos.x + 8.0f, pos.y - 25.0f),
                              a.is_overflight ? IM_COL32(150, 150, 150, 180) : IM_COL32(180, 240, 180, 220),
                              ss1.str().c_str());
            // Flight Level
            draw_list->AddText(ImVec2(pos.x + 8.0f, pos.y - 10.0f),
                              a.is_overflight ? IM_COL32(150, 150, 150, 180) : IM_COL32(180, 240, 180, 220),
                              ss2.str().c_str());
            // Squawk code (transparent)
            draw_list->AddText(ImVec2(pos.x + 8.0f, pos.y + 5.0f),
                              a.is_overflight ? IM_COL32(150, 150, 150, 100) : IM_COL32(180, 240, 180, 120),
                              ss3.str().c_str());
        }

        // Draw conflict lines
        for (auto& cf : conflicts)
        {
            const Aircraft& a = aircraft[cf.first];
            const Aircraft& b = aircraft[cf.second];
            ImVec2 pa = world_to_screen(a.x, a.y);
            ImVec2 pb = world_to_screen(b.x, b.y);
            draw_list->AddLine(pa, pb, IM_COL32(255, 80, 80, 200), 2.0f);
            ImVec2 mid((pa.x + pb.x) * 0.5f, (pa.y + pb.y) * 0.5f);
            draw_list->AddText(ImVec2(mid.x + 4, mid.y + 4), IM_COL32(255, 120, 120, 220), "CONFLICT");
        }

        // Selection
        ImVec2 io_mouse = ImGui::GetMousePos();
        bool clicked = ImGui::IsWindowHovered(ImGuiHoveredFlags_RootAndChildWindows) && ImGui::IsMouseClicked(0) && !shift_held;
        if (clicked)
        {
            float best_d = 999999.0f;
            int best_idx = -1;
            for (size_t i = 0; i < aircraft.size(); ++i)
            {
                if (aircraft[i].is_overflight) continue; // Can't select overflights

                ImVec2 pos = world_to_screen(aircraft[i].x, aircraft[i].y);
                float dx = io_mouse.x - pos.x;
                float dy = io_mouse.y - pos.y;
                float d2 = dx * dx + dy * dy;
                if (d2 < best_d && d2 < (20.0f * 20.0f))
                {
                    best_d = d2;
                    best_idx = (int)i;
                }
            }
            if (best_idx >= 0)
            {
                if (selected_index >= 0) aircraft[selected_index].selected = false;
                selected_index = best_idx;
                aircraft[selected_index].selected = true;
            }
            else
            {
                if (selected_index >= 0)
                {
                    aircraft[selected_index].selected = false;
                    selected_index = -1;
                }
            }
        }

        ImGui::End();

        // RIGHT PANEL
        ImGuiWindowFlags panel_flags = ImGuiWindowFlags_NoTitleBar |
            ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoCollapse;

        ImGui::SetNextWindowPos(ImVec2(radar_width, 0), ImGuiCond_Always);
        ImGui::SetNextWindowSize(ImVec2(right_panel_width, (float)display_h), ImGuiCond_Always);

        ImGui::Begin("RightPanel", nullptr, panel_flags);

        // SIMULATION CONTROL
        ImGui::TextColored(ImVec4(0.4f, 0.8f, 1.0f, 1.0f), "SIMULATION CONTROL");
        ImGui::Separator();

        if (ImGui::Button("Spawn Random Aircraft", ImVec2(-1, 0)))
        {
            Aircraft a;
            generateAircraft(aircraft, a, radar_range_km, aircraft.size(), true);
            aircraft.push_back(a);
        }

        ImGui::Text("Aircraft: %zu", aircraft.size());
        ImGui::Text("Conflicts: %zu", conflicts.size());

        ImGui::Dummy(ImVec2(0, 5));
        ImGui::Text("Animation Speed:");
        ImGui::SliderFloat("##speed", &animation_speed, 0.1f, 5.0f, "%.1fx");
        ImGui::SameLine();
        if (ImGui::Button("Reset##spd", ImVec2(50, 0))) {
            animation_speed = 1.0f;
        }

        ImGui::Dummy(ImVec2(0, 5));
        ImGui::Text("Wind: %03.0f° at %.0f kts", wind_heading, wind_speed_kts);

        ImGui::Dummy(ImVec2(0, 10));
        ImGui::TextColored(ImVec4(0.4f, 0.8f, 1.0f, 1.0f), "CAMERA CONTROLS");
        ImGui::Separator();

        ImGui::BulletText("Scroll: Zoom");
        ImGui::BulletText("Shift + Drag: Pan");
        ImGui::BulletText("Right Click Drag: Pan");
        ImGui::Text("Zoom: %.1fx", zoom_level);
        ImGui::Text("Offset: (%.1f, %.1f) km", camera_x, camera_y);

        if (ImGui::Button("Reset View", ImVec2(-1, 0)))
        {
            camera_x = 0.0f;
            camera_y = 0.0f;
            zoom_level = 1.0f;
        }

        ImGui::Dummy(ImVec2(0, 20));

        // COMMAND LOG SECTION
        ImGui::TextColored(ImVec4(0.4f, 0.8f, 1.0f, 1.0f), "COMMAND LOG");
        ImGui::Separator();

        float log_height = 200.0f;
        ImGui::BeginChild("CommandLog", ImVec2(0, log_height), true, ImGuiWindowFlags_HorizontalScrollbar);

        for (const auto& entry : global_command_log) {
            ImGui::TextUnformatted(entry.c_str());
        }

        // Auto-scroll to bottom
        if (ImGui::GetScrollY() >= ImGui::GetScrollMaxY()) {
            ImGui::SetScrollHereY(1.0f);
        }

        ImGui::EndChild();

        ImGui::Dummy(ImVec2(0, 10));

        // FULLSCREEN COMMAND LINE
        ImGui::TextColored(ImVec4(0.4f, 0.8f, 1.0f, 1.0f), "COMMAND LINE (F1 for help)");
        ImGui::Separator();

        bool command_executed = false;
        ImGuiInputTextFlags cmd_flags = ImGuiInputTextFlags_EnterReturnsTrue | ImGuiInputTextFlags_AutoSelectAll;

        if (ImGui::InputText("##fullcmd", command_buf, IM_ARRAYSIZE(command_buf), cmd_flags)) {
            command_executed = true;
        }

        ImGui::SameLine();
        if (ImGui::Button("Send") || command_executed) {
            std::string cmd = command_buf;
            if (!cmd.empty()) {
                // Process command
                std::string u;
                for (char c : cmd) u += (char)toupper(c);

                // Parse callsign
                size_t space_pos = u.find(' ');
                if (space_pos != std::string::npos) {
                    std::string callsign = u.substr(0, space_pos);
                    std::string command_part = u.substr(space_pos + 1);

                    // Find aircraft with this callsign
                    int ac_idx = -1;
                    for (size_t i = 0; i < aircraft.size(); ++i) {
                        if (aircraft[i].callsign == callsign) {
                            ac_idx = i;
                            break;
                        }
                    }

                    if (ac_idx >= 0 && !aircraft[ac_idx].is_overflight) {
                        Aircraft& ac = aircraft[ac_idx];

                        auto extract_number = [&](const std::string& s) -> float
                        {
                            for (int i = 0; i < (int)s.size(); i++)
                                if ((s[i] >= '0' && s[i] <= '9'))
                                    return atof(s.c_str() + i);
                            return 0.0f;
                        };

                        // Parse command
                        if (command_part.rfind("FL", 0) == 0)
                        {
                            float fl = extract_number(command_part);
                            ac.pending_altitude_ft = fl * 100.0f;
                            std::ostringstream atc_cmd, response;
                            atc_cmd << callsign << " descend and maintain flight level " << (int)fl;
                            response << callsign << ", descend and maintain FL" << (int)fl;
                            ac.setCommand(atc_cmd.str(), response.str());
                            addToCommandLog("[ATC]: " + atc_cmd.str());
                            addToCommandLog("[" + callsign + "]: " + response.str());
                            command_feedback = "Flight level assigned.";
                        }
                        else if (command_part.rfind("HDG ", 0) == 0 || command_part.rfind("HEADING ", 0) == 0)
                        {
                            float hdg = extract_number(command_part);
                            ac.pending_heading_deg = fmodf(450.0f - hdg, 360.0f);
                            std::ostringstream atc_cmd, response;
                            atc_cmd << callsign << " turn to heading " << (int)hdg;
                            response << callsign << ", turning to heading " << (int)hdg;
                            ac.setCommand(atc_cmd.str(), response.str());
                            addToCommandLog("[ATC]: " + atc_cmd.str());
                            addToCommandLog("[" + callsign + "]: " + response.str());
                            command_feedback = "Heading assigned.";
                        }
                        else if (command_part.rfind("TURN LEFT ", 0) == 0)
                        {
                            float deg = extract_number(command_part);
                            ac.pending_heading_deg = fmodf(ac.pending_heading_deg + deg, 360.0f);
                            std::ostringstream atc_cmd, response;
                            atc_cmd << callsign << " turn left " << (int)deg << " degrees";
                            response << callsign << ", turning left " << (int)deg << " degrees";
                            ac.setCommand(atc_cmd.str(), response.str());
                            addToCommandLog("[ATC]: " + atc_cmd.str());
                            addToCommandLog("[" + callsign + "]: " + response.str());
                            command_feedback = "Turning left.";
                        }
                        else if (command_part.rfind("TURN RIGHT ", 0) == 0)
                        {
                            float deg = extract_number(command_part);
                            ac.pending_heading_deg = fmodf(ac.pending_heading_deg - deg + 360.0f, 360.0f);
                            std::ostringstream atc_cmd, response;
                            atc_cmd << callsign << " turn right " << (int)deg << " degrees";
                            response << callsign << ", turning right " << (int)deg << " degrees";
                            ac.setCommand(atc_cmd.str(), response.str());
                            addToCommandLog("[ATC]: " + atc_cmd.str());
                            addToCommandLog("[" + callsign + "]: " + response.str());
                            command_feedback = "Turning right.";
                        }
                        else if (command_part.rfind("ALT ", 0) == 0 || command_part.rfind("ALTITUDE ", 0) == 0)
                        {
                            float alt = extract_number(command_part);
                            ac.pending_altitude_ft = std::max(0.0f, alt);
                            std::ostringstream atc_cmd, response;
                            atc_cmd << callsign << " descend and maintain " << (int)alt << " feet";
                            response << callsign << ", descend and maintain " << (int)alt;
                            ac.setCommand(atc_cmd.str(), response.str());
                            addToCommandLog("[ATC]: " + atc_cmd.str());
                            addToCommandLog("[" + callsign + "]: " + response.str());
                            command_feedback = "Altitude assigned.";
                        }
                        else if (command_part.rfind("CLIMB ", 0) == 0 || command_part.rfind("CLIMB TO ", 0) == 0)
                        {
                            float alt = extract_number(command_part);
                            ac.pending_altitude_ft = std::max(0.0f, alt);
                            std::ostringstream atc_cmd, response;
                            atc_cmd << callsign << " climb and maintain " << (int)alt;
                            response << callsign << ", climb and maintain " << (int)alt;
                            ac.setCommand(atc_cmd.str(), response.str());
                            addToCommandLog("[ATC]: " + atc_cmd.str());
                            addToCommandLog("[" + callsign + "]: " + response.str());
                            command_feedback = "Climbing.";
                        }
                        else if (command_part.rfind("DESCEND ", 0) == 0 || command_part.rfind("DESCEND TO ", 0) == 0)
                        {
                            float alt = extract_number(command_part);
                            ac.pending_altitude_ft = std::max(0.0f, alt);
                            std::ostringstream atc_cmd, response;
                            atc_cmd << callsign << " descend and maintain " << (int)alt;
                            response << callsign << ", descend and maintain " << (int)alt;
                            ac.setCommand(atc_cmd.str(), response.str());
                            addToCommandLog("[ATC]: " + atc_cmd.str());
                            addToCommandLog("[" + callsign + "]: " + response.str());
                            command_feedback = "Descending.";
                        }
                        else if (command_part.rfind("SPD ", 0) == 0 || command_part.rfind("SPEED ", 0) == 0)
                        {
                            float spd = extract_number(command_part);
                            ac.pending_speed_kts = std::max(0.0f, spd);
                            std::ostringstream atc_cmd, response;
                            atc_cmd << callsign << " adjust speed to " << (int)spd << " knots";
                            response << callsign << ", adjusting speed to " << (int)spd;
                            ac.setCommand(atc_cmd.str(), response.str());
                            addToCommandLog("[ATC]: " + atc_cmd.str());
                            addToCommandLog("[" + callsign + "]: " + response.str());
                            command_feedback = "Speed assigned.";
                        }
                        else if (command_part.rfind("ILS ", 0) == 0)
                        {
                            std::string rwy = command_part.substr(4);
                            ac.ils_active = true;
                            ac.ils_runway = rwy;
                            std::ostringstream atc_cmd, response;
                            atc_cmd << callsign << " cleared ILS approach runway " << rwy;
                            response << callsign << ", cleared ILS runway " << rwy;
                            ac.setCommand(atc_cmd.str(), response.str());
                            addToCommandLog("[ATC]: " + atc_cmd.str());
                            addToCommandLog("[" + callsign + "]: " + response.str());
                            command_feedback = "ILS approach activated.";
                        }
                        else if (command_part.rfind("CLEARED TO LAND", 0) == 0)
                        {
                            ac.cleared_to_land = true;
                            std::ostringstream atc_cmd, response;
                            atc_cmd << callsign << " cleared to land";
                            response << callsign << ", cleared to land";
                            ac.setCommand(atc_cmd.str(), response.str());
                            addToCommandLog("[ATC]: " + atc_cmd.str());
                            addToCommandLog("[" + callsign + "]: " + response.str());
                            command_feedback = "Cleared to land.";
                        }
                        else if (command_part.rfind("GO AROUND", 0) == 0)
                        {
                            ac.go_around = true;
                            ac.go_around_timer = 2.0f;
                            ac.cleared_to_land = false;
                            std::ostringstream atc_cmd, response;
                            atc_cmd << callsign << " go around";
                            response << callsign << ", going around";
                            ac.setCommand(atc_cmd.str(), response.str());
                            addToCommandLog("[ATC]: " + atc_cmd.str());
                            addToCommandLog("[" + callsign + "]: " + response.str());
                            command_feedback = "Go around commanded.";
                        }
                        else if (command_part.rfind("DIRECT TO ", 0) == 0)
                        {
                            std::string wp_name = command_part.substr(10);
                            // Find waypoint
                            for (const auto& wp : waypoints) {
                                if (wp.name == wp_name) {
                                    ac.direct_to_active = true;
                                    ac.direct_to_x = wp.x;
                                    ac.direct_to_y = wp.y;
                                    std::ostringstream atc_cmd, response;
                                    atc_cmd << callsign << " direct to " << wp_name;
                                    response << callsign << ", direct to " << wp_name;
                                    ac.setCommand(atc_cmd.str(), response.str());
                                    addToCommandLog("[ATC]: " + atc_cmd.str());
                                    addToCommandLog("[" + callsign + "]: " + response.str());
                                    command_feedback = "Direct to waypoint.";
                                    break;
                                }
                            }
                        }
                        else if (command_part.rfind("HOLD ", 0) == 0)
                        {
                            float hdg = extract_number(command_part);
                            ac.in_hold_pattern = true;
                            ac.hold_heading = fmodf(450.0f - hdg, 360.0f);
                            ac.hold_altitude = ac.altitude_ft;
                            ac.hold_entry_complete = false;
                            ac.hold_timer = 0.0f;

                            // Check for duration parameter
                            size_t min_pos = command_part.find("MIN");
                            if (min_pos != std::string::npos) {
                                ac.hold_duration = extract_number(command_part.substr(min_pos)) * 60.0f;
                            } else {
                                ac.hold_duration = 0.0f; // indefinite
                            }

                            std::ostringstream atc_cmd, response;
                            atc_cmd << callsign << " hold heading " << (int)hdg;
                            response << callsign << ", holding heading " << (int)hdg;
                            ac.setCommand(atc_cmd.str(), response.str());
                            addToCommandLog("[ATC]: " + atc_cmd.str());
                            addToCommandLog("[" + callsign + "]: " + response.str());
                            command_feedback = "Hold pattern entered.";
                        }
                        else if (command_part.rfind("RESUME", 0) == 0)
                        {
                            ac.in_hold_pattern = false;
                            ac.direct_to_active = false;
                            std::ostringstream atc_cmd, response;
                            atc_cmd << callsign << " resume normal navigation";
                            response << callsign << ", resuming normal navigation";
                            ac.setCommand(atc_cmd.str(), response.str());
                            addToCommandLog("[ATC]: " + atc_cmd.str());
                            addToCommandLog("[" + callsign + "]: " + response.str());
                            command_feedback = "Resuming navigation.";
                        }
                        else if (command_part.rfind("REMOVE", 0) == 0)
                        {
                            std::ostringstream atc_cmd;
                            atc_cmd << callsign << " remove from simulation";
                            addToCommandLog("[ATC]: " + atc_cmd.str());

                            if (selected_index == ac_idx) {
                                selected_index = -1;
                            } else if (selected_index > ac_idx) {
                                selected_index--;
                            }
                            aircraft.erase(aircraft.begin() + ac_idx);
                            command_feedback = "Aircraft removed.";
                        }
                        else
                        {
                            command_feedback = "Invalid or unknown command.";
                        }
                    } else {
                        command_feedback = "Aircraft not found or is overflight.";
                    }
                } else {
                    command_feedback = "Format: <callsign> <command>";
                }

                // Clear buffer
                command_buf[0] = '\0';
            }
        }

        if (!command_feedback.empty()) {
            ImGui::TextColored(ImVec4(0.7f, 1.0f, 0.7f, 1.0f), "%s", command_feedback.c_str());
        }

        ImGui::Dummy(ImVec2(0, 20));

        // AIRCRAFT CONTROL
        if (selected_index >= 0 && selected_index < (int)aircraft.size())
        {
            Aircraft& sel = aircraft[selected_index];

            ImGui::TextColored(ImVec4(0.4f, 0.8f, 1.0f, 1.0f), "AIRCRAFT CONTROL");
            ImGui::Separator();

            ImGui::SetWindowFontScale(2.0f);
            ImGui::Text("%s", sel.callsign.c_str());
            ImGui::SetWindowFontScale(1.0f);

            // Emergency display
            if (sel.emergency != EMERGENCY_NONE)
            {
                ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1.0f, 0.0f, 0.0f, 1.0f));
                ImGui::Text("EMERGENCY: %s", sel.emergency_message.c_str());
                int mins = (int)(sel.emergency_timer / 60.0f);
                int secs = (int)(sel.emergency_timer) % 60;
                ImGui::Text("Time to land: %02d:%02d", mins, secs);
                ImGui::PopStyleColor();
            }

            // Show aircraft response
            if (sel.response_timer > 0.0f)
            {
                ImGui::Dummy(ImVec2(0, 5));
                ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(0.3f, 1.0f, 0.3f, 1.0f));
                ImGui::TextWrapped("[%s]: %s", sel.callsign.c_str(), sel.last_response.c_str());
                ImGui::PopStyleColor();

                if (sel.command_delay > 0.0f)
                {
                    ImGui::TextColored(ImVec4(1.0f, 1.0f, 0.3f, 1.0f),
                        "(executing in %.1fs...)", sel.command_delay);
                }
            }

            ImGui::Dummy(ImVec2(0, 10));
            ImGui::Separator();

            // ILS Status
            ImGui::Text("ILS Approach:");
            if (sel.ils_active)
            {
                ImGui::TextColored(ImVec4(0.3f, 1.0f, 0.3f, 1.0f),
                    "Active: RWY %s", sel.ils_runway.c_str());

                if (sel.ils_established) {
                    ImGui::TextColored(ImVec4(0.3f, 1.0f, 0.3f, 1.0f), "Localizer: ESTABLISHED");
                } else {
                    ImGui::TextColored(ImVec4(1.0f, 0.5f, 0.0f, 1.0f), "Localizer: INTERCEPTING");
                }

                // Show deviations
                ImGui::Text("Localizer: %.0f m", sel.ils_localizer_deviation);
                ImGui::Text("Glideslope: %.0f ft", sel.ils_glideslope_deviation);

                if (!sel.cleared_to_land && !sel.go_around) {
                    if (ImGui::Button("Cleared to Land", ImVec2(-1, 0))) {
                        sel.cleared_to_land = true;
                        std::ostringstream atc_cmd, response;
                        atc_cmd << sel.callsign << " cleared to land";
                        response << sel.callsign << ", cleared to land";
                        sel.setCommand(atc_cmd.str(), response.str());
                        addToCommandLog("[ATC]: " + atc_cmd.str());
                        addToCommandLog("[" + sel.callsign + "]: " + response.str());
                    }
                } else if (sel.cleared_to_land) {
                    ImGui::TextColored(ImVec4(0.3f, 1.0f, 0.3f, 1.0f), "CLEARED TO LAND");
                }

                if (ImGui::Button("Disable ILS", ImVec2(-1, 0)))
                {
                    sel.ils_active = false;
                    sel.ils_runway = "";
                    sel.cleared_to_land = false;
                    std::ostringstream atc_cmd, response;
                    atc_cmd << sel.callsign << " cancel ILS approach";
                    response << sel.callsign << ", ILS approach canceled";
                    sel.setCommand(atc_cmd.str(), response.str());
                    addToCommandLog("[ATC]: " + atc_cmd.str());
                    addToCommandLog("[" + sel.callsign + "]: " + response.str());
                }
            }
            else
            {
                for (const auto& rwy : runways)
                {
                    std::string btn_label = "ILS RWY " + rwy.name;
                    if (ImGui::Button(btn_label.c_str(), ImVec2(-1, 0)))
                    {
                        sel.ils_active = true;
                        sel.ils_runway = rwy.name;
                        sel.ils_established = false;
                        std::ostringstream atc_cmd, response;
                        atc_cmd << sel.callsign << " cleared ILS approach runway " << rwy.name;
                        response << sel.callsign << ", cleared ILS runway " << rwy.name;
                        sel.setCommand(atc_cmd.str(), response.str());
                        addToCommandLog("[ATC]: " + atc_cmd.str());
                        addToCommandLog("[" + sel.callsign + "]: " + response.str());
                    }
                }
            }

            ImGui::Separator();

            // Hold pattern control
            ImGui::Text("Hold Pattern:");
            if (sel.in_hold_pattern) {
                ImGui::TextColored(ImVec4(0.3f, 1.0f, 0.3f, 1.0f), "ACTIVE");
                if (ImGui::Button("Resume Navigation", ImVec2(-1, 0))) {
                    sel.in_hold_pattern = false;
                    std::ostringstream atc_cmd, response;
                    atc_cmd << sel.callsign << " resume normal navigation";
                    response << sel.callsign << ", resuming normal navigation";
                    sel.setCommand(atc_cmd.str(), response.str());
                    addToCommandLog("[ATC]: " + atc_cmd.str());
                    addToCommandLog("[" + sel.callsign + "]: " + response.str());
                }
            } else {
                if (ImGui::Button("Enter Hold Pattern", ImVec2(-1, 0))) {
                    sel.in_hold_pattern = true;
                    sel.hold_heading = sel.heading_deg;
                    sel.hold_altitude = sel.altitude_ft;
                    sel.hold_entry_complete = false;
                    sel.hold_duration = 0.0f;
                    std::ostringstream atc_cmd, response;
                    atc_cmd << sel.callsign << " hold present heading";
                    response << sel.callsign << ", holding present heading";
                    sel.setCommand(atc_cmd.str(), response.str());
                    addToCommandLog("[ATC]: " + atc_cmd.str());
                    addToCommandLog("[" + sel.callsign + "]: " + response.str());
                }
            }

            ImGui::Separator();

            // Direct to waypoint
            ImGui::Text("Direct to Waypoint:");
            for (const auto& wp : waypoints) {
                std::string btn_label = "Direct to " + wp.name;
                if (ImGui::Button(btn_label.c_str(), ImVec2(-1, 0))) {
                    sel.direct_to_active = true;
                    sel.direct_to_x = wp.x;
                    sel.direct_to_y = wp.y;
                    std::ostringstream atc_cmd, response;
                    atc_cmd << sel.callsign << " direct to " << wp.name;
                    response << sel.callsign << ", direct to " << wp.name;
                    sel.setCommand(atc_cmd.str(), response.str());
                    addToCommandLog("[ATC]: " + atc_cmd.str());
                    addToCommandLog("[" + sel.callsign + "]: " + response.str());
                }
            }

            ImGui::Separator();

            // Altitude controls with OK button
            ImGui::Text("Altitude: %.0f ft", sel.altitude_ft);
            float display_target = (sel.command_delay > 0.0f) ? sel.pending_altitude_ft : sel.target_altitude_ft;
            if (fabs(display_target - sel.altitude_ft) > 10.0f)
            {
                ImGui::SameLine();
                ImGui::TextColored(ImVec4(0.5f, 0.8f, 1.0f, 1.0f), "-> %.0f ft", display_target);
            }

            static float new_altitude = sel.altitude_ft;
            new_altitude = sel.pending_altitude_ft;
            ImGui::PushItemWidth(200);
            if (ImGui::InputFloat("##newalt", &new_altitude, 100.0f, 1000.0f, "%.0f ft")) {
                new_altitude = std::max(0.0f, new_altitude);
            }
            ImGui::PopItemWidth();
            ImGui::SameLine();
            if (ImGui::Button("Set##alt")) {
                float old = sel.altitude_ft;
                sel.pending_altitude_ft = new_altitude;
                float diff = fabs(sel.pending_altitude_ft - old);
                std::ostringstream atc_cmd, response;
                if (new_altitude > old) {
                    atc_cmd << sel.callsign << " climb and maintain " << (int)new_altitude;
                    response << sel.callsign << ", climbing to " << (int)new_altitude;
                } else {
                    atc_cmd << sel.callsign << " descend and maintain " << (int)new_altitude;
                    response << sel.callsign << ", descending to " << (int)new_altitude;
                }
                sel.setCommand(atc_cmd.str(), response.str());
                addToCommandLog("[ATC]: " + atc_cmd.str());
                addToCommandLog("[" + sel.callsign + "]: " + response.str());
            }

            ImGui::Separator();

            // Heading controls with OK button
            ImGui::Text("Heading: %.0f°", fmodf(450.0f - sel.heading_deg, 360.0f));
            float display_heading = (sel.command_delay > 0.0f) ? sel.pending_heading_deg : sel.target_heading_deg;
            if (fabs(angle_difference(display_heading, sel.heading_deg)) > 1.0f)
            {
                ImGui::SameLine();
                ImGui::TextColored(ImVec4(0.5f, 0.8f, 1.0f, 1.0f), "-> %.0f°", fmodf(450.0f - display_heading, 360.0f));
            }

            static float new_heading = fmodf(450.0f - sel.heading_deg, 360.0f);
            new_heading = fmodf(450.0f - sel.pending_heading_deg, 360.0f);
            ImGui::PushItemWidth(200);
            if (ImGui::InputFloat("##newhdg", &new_heading, 5.0f, 10.0f, "%.0f°")) {
                new_heading = fmodf(new_heading + 360.0f, 360.0f);
            }
            ImGui::PopItemWidth();
            ImGui::SameLine();
            if (ImGui::Button("Set##hdg")) {
                float old = sel.heading_deg;
                sel.pending_heading_deg = fmodf(450.0f - new_heading, 360.0f);
                float diff = angle_difference(sel.pending_heading_deg, old);
                std::ostringstream atc_cmd, response;
                if (diff > 0) {
                    atc_cmd << sel.callsign << " turn left " << (int)fabs(diff) << " degrees";
                    response << sel.callsign << ", turning left " << (int)fabs(diff) << " degrees";
                } else {
                    atc_cmd << sel.callsign << " turn right " << (int)fabs(diff) << " degrees";
                    response << sel.callsign << ", turning right " << (int)fabs(diff) << " degrees";
                }
                sel.setCommand(atc_cmd.str(), response.str());
                addToCommandLog("[ATC]: " + atc_cmd.str());
                addToCommandLog("[" + sel.callsign + "]: " + response.str());
            }

            ImGui::Separator();

            // Speed controls with OK button
            ImGui::Text("Speed: %.0f kts", sel.speed_kts);
            float display_speed = (sel.command_delay > 0.0f) ? sel.pending_speed_kts : sel.target_speed_kts;
            if (fabs(display_speed - sel.speed_kts) > 1.0f)
            {
                ImGui::SameLine();
                ImGui::TextColored(ImVec4(0.5f, 0.8f, 1.0f, 1.0f), "-> %.0f kts", display_speed);
            }

            static float new_speed = sel.speed_kts;
            new_speed = sel.pending_speed_kts;
            ImGui::PushItemWidth(200);
            if (ImGui::InputFloat("##newspd", &new_speed, 5.0f, 10.0f, "%.0f kts")) {
                new_speed = std::max(0.0f, new_speed);
            }
            ImGui::PopItemWidth();
            ImGui::SameLine();
            if (ImGui::Button("Set##spd")) {
                float old = sel.speed_kts;
                sel.pending_speed_kts = new_speed;
                float diff = fabs(sel.pending_speed_kts - old);
                std::ostringstream atc_cmd, response;
                if (new_speed > old) {
                    atc_cmd << sel.callsign << " increase speed to " << (int)new_speed;
                    response << sel.callsign << ", increasing speed to " << (int)new_speed;
                } else {
                    atc_cmd << sel.callsign << " reduce speed to " << (int)new_speed;
                    response << sel.callsign << ", reducing speed to " << (int)new_speed;
                }
                sel.setCommand(atc_cmd.str(), response.str());
                addToCommandLog("[ATC]: " + atc_cmd.str());
                addToCommandLog("[" + sel.callsign + "]: " + response.str());
            }
        }
        else
        {
            ImGui::TextColored(ImVec4(0.4f, 0.8f, 1.0f, 1.0f), "AIRCRAFT CONTROL");
            ImGui::Separator();
            ImGui::TextColored(ImVec4(0.7f, 0.7f, 0.7f, 1.0f), "No aircraft selected.");
            ImGui::Text("Click on an aircraft");
            ImGui::Text("to control it.");
            ImGui::TextColored(ImVec4(0.5f, 0.5f, 0.5f, 1.0f), "(Overflights cannot be selected)");
        }

        ImGui::End();

        // Render
        ImGui::Render();
        glViewport(0, 0, display_w, display_h);
        glClearColor(0.05f, 0.05f, 0.05f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);
        ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

        glfwSwapBuffers(window);
    }

    ImGui_ImplOpenGL3_Shutdown();
    ImGui_ImplGlfw_Shutdown();
    ImGui::DestroyContext();
    glfwDestroyWindow(window);
    glfwTerminate();

    return 0;
}